on:
  push:
    branches:
       google-cloud-run
name: Linux_Container_Workflow

jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/634781802413/locations/global/workloadIdentityPools/hclouddemo/*'
        service_account: '634781802413-compute@developer.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        service: 'hello-cloud-run'
        image: 'gcr.io/cr-test-345909/helloworld:latest'

    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
