on:
  push:
    branches:
       cci
name: Linux_Container_Workflow

env:
  REGION_ID: cn-north-4                  # set this to your preferred huaweicloud region, e.g. cn-north-4
  ACCESS_KEY_ID: ${{ secrets.ACCESSKEY }}             # set this to your huaweicloud access-key-id
  ACCESS_KEY_SECRET: ${{ secrets.SECRETACCESSKEY }}               # set this to your huaweicloud access-key-secret
  SWR_ORGANIZATION:  hcloudcli   # SWR 组织名
  IMAGE_NAME: ccidemo       # 镜像名称

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: Kubectl tool installer
          id: install-kubectl
          uses: Azure/setup-kubectl@v2.1
        - name: kubectl
          run: |
            curl -LO "https://cci-iam-authenticator.obs.cn-north-4.myhuaweicloud.com/latest/linux-amd64/cci-iam-authenticator"
            chmod +x ./cci-iam-authenticator
            mv ./cci-iam-authenticator /usr/local/bin
            cci-iam-authenticator generate-kubeconfig --cci-endpoint=https://cci.cn-north-4.myhuaweicloud.com --ak=${{ env.ACCESS_KEY_ID }} --sk=${{ secrets.SECRETACCESSKEY }}
            kubectl get ns
          
        
#         - name: Log in to HuaweiCloud SWR
#           uses: huaweicloud/swr-login@v1
#           with:
#             region: ${{ env.REGION_ID }}
#             access-key-id: ${{ secrets.ACCESSKEY }}
#             access-key-secret: ${{ secrets.SECRETACCESSKEY }}

#         - name: Build, tag, and push image to HuaweiCloud SWR
#           id: build-image
#           env:
#             SWR_REGISTRY: swr.${{ env.REGION_ID }}.myhuaweicloud.com
#             SWR_ORGANIZATION: ${{ env.SWR_ORGANIZATION }}
#             IMAGE_TAG: ${{ github.sha }}
#             IMAGE_NAME: ${{ env.IMAGE_NAME }}
#           run: |
#             docker build -t $SWR_REGISTRY/$SWR_ORGANIZATION/$IMAGE_NAME:$IMAGE_TAG .
#             docker push $SWR_REGISTRY/$SWR_ORGANIZATION/$IMAGE_NAME:$IMAGE_TAG
#             echo "::set-output name=image::$SWR_REGISTRY/$SWR_ORGANIZATION/$IMAGE_NAME:$IMAGE_TAG"
